name: Generate Index JSON

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Lấy toàn bộ lịch sử để check ngày tháng

      - name: Generate index.json
        run: |
          echo "[" > index.json
          FIRST=true
          
          # Tìm tất cả thư mục có chứa file khoa-hoc.json
          # Sắp xếp theo ngày commit mới nhất của thư mục đó (git log)
          find . -maxdepth 2 -name "khoa-hoc.json" | while read filename; do
            dir=$(dirname "$filename")
            dirname=$(basename "$dir")
            
            # Bỏ qua thư mục . (hiện tại)
            if [ "$dirname" == "." ]; then continue; fi

            # Lấy ngày update cuối cùng của thư mục này
            last_update=$(git log -1 --format="%cI" -- "$dir")
            
            # Tìm file ảnh (jpg, jpeg, png, webp)
            img=""
            if [ -f "$dir/anh-khoa-hoc.jpg" ]; then img="$dir/anh-khoa-hoc.jpg"; fi
            if [ -f "$dir/anh-khoa-hoc.jpeg" ]; then img="$dir/anh-khoa-hoc.jpeg"; fi
            if [ -f "$dir/anh-khoa-hoc.png" ]; then img="$dir/anh-khoa-hoc.png"; fi
            if [ -f "$dir/anh-khoa-hoc.webp" ]; then img="$dir/anh-khoa-hoc.webp"; fi

            # Xử lý dấu phẩy JSON
            if [ "$FIRST" = true ]; then
              FIRST=false
            else
              echo "," >> index.json
            fi

            # Ghi vào JSON (Escape dấu ngoặc kép trong tên folder)
            clean_dirname=$(echo "$dirname" | sed 's/"/\\"/g')
            
            echo "  {" >> index.json
            echo "    \"name\": \"$clean_dirname\"," >> index.json
            echo "    \"folder\": \"$clean_dirname\"," >> index.json
            echo "    \"file\": \"$dirname/khoa-hoc.json\"," >> index.json
            echo "    \"thumb\": \"$img\"," >> index.json
            echo "    \"updated\": \"$last_update\"" >> index.json
            echo "  }" >> index.json
          done

          echo "]" >> index.json

          # Format lại JSON cho đẹp (Optional)
          # cat index.json | python3 -m json.tool > index_pretty.json && mv index_pretty.json index.json

      - name: Commit and Push index.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.json
          # Chỉ commit nếu có thay đổi
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update index.json" && git push)
