name: Update Course Index

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Cho phép bấm nút chạy thủ công

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate JSON with Python
        run: |
          python3 -c "
          import os
          import json
          import subprocess

          courses = []
          # Quét thư mục hiện tại
          for root, dirs, files in os.walk('.'):
              # Bỏ qua thư mục .git và .github
              if '.git' in root: continue
              
              if 'khoa-hoc.json' in files:
                  folder_path = root
                  folder_name = os.path.basename(folder_path)
                  
                  # Lấy đường dẫn file json (bỏ ./ ở đầu)
                  file_path = os.path.join(root, 'khoa-hoc.json').replace('./', '').replace('.\\\\', '')
                  
                  # Tìm ảnh
                  thumb = ''
                  for ext in ['jpg', 'jpeg', 'png', 'webp', 'JPG', 'PNG']:
                      img_name = f'anh-khoa-hoc.{ext}'
                      if img_name in files:
                          thumb = os.path.join(root, img_name).replace('./', '').replace('.\\\\', '')
                          break
                  
                  # Lấy ngày update cuối cùng từ git
                  try:
                      date_cmd = ['git', 'log', '-1', '--format=%cI', '--', folder_path]
                      updated_time = subprocess.check_output(date_cmd).decode().strip()
                  except:
                      updated_time = ''

                  courses.append({
                      'name': folder_name,
                      'folder': folder_name,
                      'file': file_path,
                      'thumb': thumb,
                      'updated': updated_time
                  })

          # Ghi ra file index.json
          with open('index.json', 'w', encoding='utf-8') as f:
              json.dump(courses, f, indent=2, ensure_ascii=False)
          
          print(f'Đã tìm thấy {len(courses)} khóa học.')
          "

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add index.json
          # Kiểm tra xem có thay đổi không mới commit
          if git diff --staged --quiet; then
            echo "Không có thay đổi nào để commit."
          else
            git commit -m "Auto update index.json [Skip CI]"
            git push
          fi
